---
title: |
  | What should we do and why?
  | Work principles for behavioral insights teams.
author: Jake Bowers
institute: | 
     | Political Science and Statistics, University of Illinois @ Urbana-Champaign
     | Fellow, White House Social and Behavioral Sciences Team
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output:
  beamer_presentation:
    keep_tex: yes
    latex_engine: xelatex
    slide_level: 2
    template: sbst.beamer
    toc: yes
  ioslides_presentation:
    css: sbstpresentation.css
    logo: ../graphics/SBSTLightBulb.png
    smaller: yes
---


```{r setup, include=FALSE, echo=FALSE, cache=FALSE}
## To compile this by hand do:
## library(rmarkdown)
## render("presentation.Rmd")
## OR 
## Rscript -e "library(methods);library(knitr); knit('presentation.Rmd',output='presentation.md')"
## On my system then: 
## pandoc +RTS -K512m -RTS presentation.utf8.md --to beamer --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash --output presentation.pdf --template sbst.beamer --table-of-contents --slide-level 2 --highlight-style tango --latex-engine /Library/TeX/texbin/xelatex 

## the 'toc: yes' line above tricks pandoc into running latex twice so that we can see the nice logos

# Some customization.  You can alter or delete as desired (if you know what you are doing).
# knitr settings to control how R chunks work.

require(knitr)
opts_chunk$set(
  size = "scriptsize",    # slightly smaller font for code
  echo = TRUE,
  results = 'markup',
  strip.white = TRUE,
  cache = FALSE,
  highlight = TRUE,
  width.cutoff = 60,
  out.width = '.9\\textwidth',
  message = FALSE,
  comment = NA,
  tidy = TRUE,     # display code as typed
  tidy.opts = list(blank = FALSE, width.cutoff = 60))
```

# Introducing Behavioral Insights Teams

## Behavioral Insights Teams in Government

President Barak Obama USA Executive Order 13707 "Using Behavioral Insights To Better Serve the American People":

> A growing body of evidence demonstrates that behavioral science insights---research findings from fields such as behavioral economics and psychology about how people make decisions and act on them---can be used to design government policies to better serve the American people.

[The UK Nudge Unit](http://www.behaviouralinsights.co.uk/about-us/)

\medskip

[The White House SBST](http://sbst.gov)

\medskip

[The EU](https://ec.europa.eu/jrc/en/event/conference/biap-2016#country-overviews)

\medskip

[New South Wales Intro to Behavioral Insights Teams](https://www.youtube.com/watch?v=pDub6gG1yxw&feature=youtu.be)

## Person oriented government from Science and Design

BI teams translate (and extend) knowledge from (mostly) randomized experiment-based workflows into public policy.

\medskip

UX (user experience) designers interview and observe users of products throughout the cycle of iterative production.

(Quote about how interviews give them "why" where as "demographics" only give "how", literature and methods (even qualitative methods) from behavioral science is not a part of the vocublary).

(Show github for 18F research on a project)

# A reason for BI: Science in the House.


## What follows from valuing science? 

(insert shot from slack)

Why not Behavioral Claims Teams?  Why does science produce "insights"? 

\medskip

Principles of Science

1) No one study produces certain knowledge (there is no certain knowledge). 
2) No one person produces certain knowledge. Investigators must be comfortable with uncertainty and doubt.

\bigskip

BTW, these ideas enable frequentist statistical inference: a $p$-value / confidence interval is a $p$-value/confidence interval, no more no less.

## What follows from a person oriented approach to public policy?

Stuff

# Concrete Actions for 2016

## Action 1: Use plain text

Writing memos, reports, or analyses in formats that are propriety and/or likely to change quickly and/or cost money to read raises barriers to collaboration across both space (with others) and time (with the team itself should it desire to use materials from past studies for the future.)^[This poses a challenge for groups where the government dictates the tools.] This essay, for example, is written in [markdown](https://daringfireball.net/projects/markdown/).^[Specifically, it uses [pandoc](http://pandoc.org/) flavored markdown.]

## Action 2: Use open-source and multi-platform tools

Plain text code written for interpretation by an expensive and single platform computing language may be readable in the future, but will be of little use to those who desire to help or learn from the team. This suggests that teams only use tools like R or python or other open-source analysis and/or markup languages that are available on free operating systems and across platforms.

## Action 2a: Assume others will want to reproduce the work.

The fact that one has written open source code written in plain text does not mean that others can effectively learn from or copy and improve on one's work. This means that all analyses should be written as if someone else, who is not a part of the team's social network, ought to be able to reproduce the analyses of the team (to the extent possible given data sharing limitations). Tools here include [Rmarkdown](http://rmarkdown.rstudio.com/) and processes for tracking dependencies among files like the [make](http://robjhyndman.com/hyndsight/makefiles/) system and [R packages](http://r-pkgs.had.co.nz/).^[Insert versions for python.]

## Action 3: Work in the Open Take advantage of the cloud

My favorite way to work in the open right now is to use [GitHub](http://github.com) because it not only encourages a workflow in which people copy and improve and change others' code, but prevents old files from being clobbered with new files, tracks and threads discussions about topics, and enables online editing and easy website creation for quick sharing of documents and results.



# End Matter

## Sources and Inspirations

This document builds on the [*commitment of the federal government to
openness*](https://www.whitehouse.gov/open) and especially on my 
interpretation of the detailed [*US Open Government National Action Plan
3.0*](https://www.whitehouse.gov/sites/default/files/microsites/ostp/final_us_open_government_national_action_plan_3_0.pdf)

\bigskip

The injunction to "work in the open" (and internally to "share not send") comes from [*18F*](https://18f.gsa.gov/2014/07/31/working-in-public-from-day-1/)


\bigskip

This document is currently hosted on github at <http://github/sbstusa/transparency>. Comments welcome. 


## More inspiration from 18F

[18F Design Principles](https://github.com/18F/myusa-ux/blob/master/research/memos/design-principles.md)

[[18F Design Principles Definition](https://pages.18f.gov/design-principles-guide/define/)

[18F Design and Production Process](https://pages.18f.gov/lean-product-design/)


## More Inspiration: Statements of Principles

[EGAP Design Principles](http://egap.org/egap-statement-of-principles) 

[Australia Government Design Principles](http://www.designprinciplesftw.com/collections/australia-designgov-principles)

[Code for America Design Principles](http://www.designprinciplesftw.com/collections/principles-for-21st-century-government)

